"""Abstract Base Class for LLM Providers (FR-401, NFR-08).

Ensures all LLM backends (OpenAI, Anthropic, Groq, Ollama, Mock) can be swapped
purely via LLM_PROVIDER configuration without modifying RAG or chat routing.
"""

from abc import ABC, abstractmethod
from typing import List, Optional
from core.models import ChatMessage


class BaseLLMProvider(ABC):
    """Abstract interface for LLM text generation."""

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Name of the LLM provider."""
        pass

    @property
    @abstractmethod
    def model_name(self) -> str:
        """Name of the active model."""
        pass

    @abstractmethod
    async def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        history: Optional[List[ChatMessage]] = None,
        temperature: Optional[float] = None,
    ) -> str:
        """Generate a grounded response given system context and conversation history."""
        pass

    async def stream_generate(
        self,
        system_prompt: str,
        user_prompt: str,
        history: Optional[List[ChatMessage]] = None,
        temperature: Optional[float] = None,
    ):
        """Asynchronously yield text tokens as they are generated by the model."""
        full_text = await self.generate(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            history=history,
            temperature=temperature,
        )
        yield full_text

